backend:
  name: git-gateway
  branch: main

repo: torn-flight-club/flight-club-wiki

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "docs_public"
    label: "Public Docs"
    folder: "docs-public"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "sidebar_position", label: "Sidebar Position", widget: "number", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "docs_internal"
    label: "Internal Docs"
    folder: "docs-internal"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "sidebar_position", label: "Sidebar Position", widget: "number", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
